version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: commerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend
    container_name: server
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=commerce
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password
      - JWT_SECRET_KEY=1e463576441b923b983d4b7dcc5338af710f6bc52e3653c89f065611dd329cc3
    restart: unless-stopped

volumes:
  postgres_data: